name: GitHub Pages for my blog

on:
  # マージされたプルリクエストは常にプッシュになる
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub Pagesへデプロイするためのコミットはbotが行うものとする
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: deploy to GitHub Pages
        run: |
          git config --global user.name ${{ github.repository_owner }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          npm install --location=global yarn
          yarn install
          yarn deploy
